### ISSUE TITLE
Publish for 0.18

### ISSUE THREAD

**Issue by mlsteele** [elm-lang/regex#1]
Could you publish this package for Elm 0.18? Or @evancz's [repo](https://github.com/elm-lang/regex).

```
$ elm --version
0.18.0
$ elm-package install elm-lang/regex
Error: Could not find any packages named elm-lang/regex.
$ elm-package install evancz/regex
Error: Could not find any packages named evancz/regex.
```

I'm looking for a function `String -> Maybe Regex` and found this repo from https://github.com/elm-lang/core/issues/722 after the core `Regex.regex` let me down. I'm very new to Elm so forgive me if this is a misguided request.

**Comment by mlsteele** [comment]
I tried to work around this issue for the time being by vendoring this `regex` project into my repo using [this method](https://stackoverflow.com/a/45648851). But then ran into a snag where it conflicted with the 0.18 `Regex` package. If there was a way to simply import as Regex2 that would work. Next step is renaming all the occurrences of `Regex` with `Regex2` in my local copy. So this is another case for https://github.com/elm-lang/elm-compiler/issues/1625.

**Comment by evancz** [comment]
Hey, sorry you are running into trouble along these lines. These cases is part of what motivated the new API! But this package is slated to come out with 0.19 due to a confluence of other factors. One thing you could do in the meantime is override what `new RegExp` means in the context where you run Elm. Perhaps like this:

```javascript
(function() {
function RegExp(str, settings) {
    try {
        return new window.RegExp(str, settings);
    } catch(e) {
        return /.^/;
    }
}
// elm program
}())
```

Obviously this is not ideal at all, but coordinating an Elm release is quite tricky, and I think something like the code shown here may be the best thing viable until the release is possible.
